### ISSUE TITLE
some questions.

### ISSUE THREAD

**Issue by liusy58** [downdemo/Cpp-Concurrency-in-Action-2ed#2]
你好，我最近也在看这本书，我有一些疑问想跟你探讨一下不知你是否方便？

1. P20 ，The act of calling join() also cleans up any storage associated with the thread, so the std::thread object is no longer associated with the now-finished thread; it isn’t associated with any thread. 这句话我没太懂？

2. P22 The copy constructor and copy-assignment operators are marked =delete to ensure
that they’re not automatically provided by the compiler. Copying or assigning such an
object would be dangerous, because it might then outlive the scope of the thread it was
joining. By declaring them as deleted, any attempt to copy a thread_guard object will
generate a compilation error.  如果不将copy-assignment 定为 deleted的话，为什么是危险的呀？能否举一个例子？

**Comment by downdemo** [comment]
1. Call join() to waits for the thread to finish its execution;
2. May double free RAII resource if copyable.

PS:
1. Cannot see your thoughts on questions;
2. Not suitable for asking questions here.

**Comment by downdemo** [comment]
1. Call join() to wait for the thread to finish its execution;
2. May double free RAII resource if copyable.

PS:
1. Cannot see your thoughts on questions;
2. Not suitable for asking questions here.
