### ISSUE TITLE
在“8.1.2　以递归方式划分数据”中的 parallel_quick_sort不能正常运行

### ISSUE THREAD

**Issue by peacess** [downdemo/Cpp-Concurrency-in-Action-2ed#5]
下面是运行代码：
int main(){
  std::list<int> data = {5,1,2,9,100,8};
  auto sorted_data = parallel_quick_sort(data);
  for(auto it: sorted_data ){
    printf("%d", it);
  }
}
出错信息：
terminate called after throwing an instance of 'EmptyStack'
  what():  empty stack!
[1] + Done                       "/usr/bin/gdb" --interpreter=mi --tty=${DbgTerm} 0<"/tmp/Microsoft-MIEngine-In-m25ftpou.0wk" 1>"/tmp/Microsoft-MIEngine-Out-xpupxdid.5th"

**Comment by downdemo** [comment]
test results of https://godbolt.org/z/j57Terzx5 is OK, gcc 8.5, -std=c++17
