### ISSUE TITLE
第3章 03_synchronizing_concurrent_operation的信号量小节的acquire()问题

### ISSUE THREAD

**Issue by ouuyuj** [downdemo/Cpp-Concurrency-in-Action-2ed#6]
[acquire()](https://en.cppreference.com/w/cpp/thread/counting_semaphore/acquire)的描述为
**Atomically decrements the internal counter by 1 if it is greater than ​0​; otherwise blocks until it is greater than ​0​ and can successfully decrement the internal counter.**
并不是[acquire()即 P 操作，会在信号量值不小于 0 时将信号量减 1](https://github.com/downdemo/Cpp-Concurrency-in-Action-2ed/blob/master/docs/03_synchronizing_concurrent_operation.md) 
应该修改acquire()即 P 操作，会在信号量值为不小于等于0 或者 大于0时将信号量减 1

**Comment by downdemo** [comment]
Thx, done.
